spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/appointments}
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: false
        globally_quoted_identifiers_skip_column_definitions: true
        batch_fetch_style: dynamic
        default_batch_fetch_size: 16
        jdbc:
          batch_size: 16
          order_inserts: true
          order_updates: true
    show-sql: true
    generate-ddl: true

server:
  servlet:
    context-path: /med-manager/api/v1
  port: 8080
  host: http://localhost
